export type Category = "food" | "drink";

export type FoodSubcategory =
  | "pancake"
  | "french_toast"
  | "eggs_benedict"
  | "sandwich"
  | "fritter"
  | "burger"
  | "lunch";

export type DrinkSubcategory =
  | "coffee"
  | "tea"
  | "soft"
  | "alcohol";

export type Subcategory = FoodSubcategory | DrinkSubcategory;

export type MediaItem = { type: "image" | "video"; url: string };

export interface MenuItem {
  id: string;
  category: Category;
  subcategory: Subcategory;
  name: string;
  nameEn: string;
  description: string;
  price: number;
  image: string;           // カート等のサムネ用（最初の image メディア）
  images?: string[];       // 画像 URL のみの配列（legacy / ItemModal 互換）
  video?: string | null;
  media?: MediaItem[];     // 並び順そのまま。配列先頭 = 一覧カバー
  tag?: string; // "人気" | "おすすめ" | "限定"
  calories?: number | null;
  servingTimeMin?: number | null;
  isTakeout?: boolean;
}

// ─── 実店舗写真（public/images/ 配下）────────────────────────
const LOCAL = {
  p1:  "/images/pancake/p1.webp",   // プレーン（バター・メープル）
  p2:  "/images/pancake/p2.webp",   // フルーツ&フルーツ
  p3:  "/images/pancake/p3.webp",   // チョコ＆バナナ（アイスクリーム）
  p4:  "/images/pancake/p4.webp",   // チョコマシュマロ（ダークソース）
  p5:  "/images/pancake/p5.webp",   // マスカルポーネ＆エスプレッソ
  ft1: "/images/pancake/ft1.webp",  // フレンチトースト
  c1:  "/images/cafe/c1.webp",      // ブレンドコーヒー
  c2:  "/images/cafe/c2.webp",      // カフェラテ（ラテアート）
  c3:  "/images/cafe/c3.webp",      // カプチーノ（花柄ラテアート）
};

// ─── Unsplash プレースホルダー────────────────────────────────
const IMG = {
  pancake:   "https://images.unsplash.com/photo-1554520735-0a6b8b6ce8b7?w=600&q=80",
  benedict:  "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600&q=80",
  benedict2: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&q=80",
  sandwich:  "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
  sandwich2: "https://images.unsplash.com/photo-1540713434306-58505cf1b6fc?w=600&q=80",
  fritter:   "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=600&q=80",
  fritter2:  "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=600&q=80",
  burger:    "https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&q=80",
  burger2:   "https://images.unsplash.com/photo-1602030028438-4cf153cbdf4c?w=600&q=80",
  curry:     "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&q=80",
  fish:      "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&q=80",
  omelet:    "https://images.unsplash.com/photo-1506354666786-959d6d497f1a?w=600&q=80",
  hamburg:   "https://images.unsplash.com/photo-1614777735417-4bf6a6c6d396?w=600&q=80",
  pasta:     "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=600&q=80",
  salad:     "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
  chicken:   "https://images.unsplash.com/photo-1598103442097-8b74394b95c3?w=600&q=80",
  rice:      "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80",
  latte:     "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&q=80",
  icecoffee: "https://images.unsplash.com/photo-1517701604599-bb29b565090b?w=600&q=80",
  cocoa:     "https://images.unsplash.com/photo-1517756338630-84f7e2dd4d6a?w=600&q=80",
  milk:      "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&q=80",
  tea:       "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&q=80",
  juice:     "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=600&q=80",
  beer:      "https://images.unsplash.com/photo-1608270586620-248524c67de9?w=600&q=80",
  cocktail:  "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&q=80",
  wine:      "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&q=80",
  sparkling: "https://images.unsplash.com/photo-1578911373434-0cb395d2cbfb?w=600&q=80",
};

export const menuItems: MenuItem[] = [

  // ─── PANCAKE ─────────────────────────────────────────────
  {
    id: "p1",
    category: "food",
    subcategory: "pancake",
    name: "プレーン",
    nameEn: "Plain Pancake",
    description: "毎朝丁寧に焼き上げる、YORKYSを代表する看板メニューです。ふんわりしっとりとした絶妙な食感の生地は、長年磨き上げてきた独自のレシピで仕上げています。北海道産の厳選有機バターのコクと、カナダ産天然メープルシロップの豊かな香りと甘みがひとつになった、シンプルだからこそ奥深い味わいの一皿。パンケーキ好きにこそ食べていただきたい定番の美味しさです。",
    price: 1100,
    image: LOCAL.p1,
    tag: "人気",
  },
  {
    id: "p2",
    category: "food",
    subcategory: "pancake",
    name: "キャラメルナッツ",
    nameEn: "Caramel Nut Pancake",
    description: "濃厚なキャラメルソースをたっぷりとかけ、香ばしいローストナッツをトッピングしたリッチな一皿。アーモンド、くるみ、カシューナッツを使用したミックスナッツは食べ応え抜群。ふんわりとしたパンケーキ生地と、甘さとほろ苦さが絶妙なキャラメルの組み合わせが絶品です。スイーツ感覚でお楽しみいただける、特別感あふれるパンケーキです。",
    price: 1210,
    image: IMG.pancake,
  },
  {
    id: "p3",
    category: "food",
    subcategory: "pancake",
    name: "チョコ＆バナナ",
    nameEn: "Chocolate & Banana Pancake",
    description: "なめらかなチョコレートソースとフレッシュなバナナ、バニラアイスクリームを添えたデザート感覚のパンケーキ。温かいパンケーキと冷たいアイスクリームの温度差が楽しく、口の中でとろける贅沢な味わいを演出します。甘さ控えめのビタースイートなチョコレートが素材の美味しさを引き立て、子供から大人まで楽しめる人気の一皿です。",
    price: 1210,
    image: LOCAL.p3,
  },
  {
    id: "p4",
    category: "food",
    subcategory: "pancake",
    name: "マスカルポーネ＆エスプレッソ",
    nameEn: "Mascarpone & Espresso Pancake",
    description: "イタリアのデザート「ティラミス」からインスピレーションを受けたパンケーキ。濃厚なマスカルポーネクリームのまろやかな甘みと、本格エスプレッソソースのほろ苦さが絶妙なバランスを生み出します。コーヒーの深い風味とチーズクリームのコクが重なり合う、大人のための贅沢な一皿。食後のデザートとしても人気です。",
    price: 1408,
    image: LOCAL.p5,
  },
  {
    id: "p5",
    category: "food",
    subcategory: "pancake",
    name: "チョコマシュマロ",
    nameEn: "Chocolate Marshmallow Pancake",
    description: "夙川本店限定のスペシャルパンケーキ。とろけるダークチョコレートソースとふわふわマシュマロをたっぷりと使ったデザート感覚の一皿です。グリルしたマシュマロの芳ばしい香りと、濃厚なチョコレートのコクが絶妙にマッチ。まるでスモアのような楽しい食感と味わいが楽しめます。数量限定のため、お早めにどうぞ。",
    price: 1375,
    image: LOCAL.p4,
    tag: "限定",
  },
  {
    id: "p6",
    category: "food",
    subcategory: "pancake",
    name: "フルーツ&フルーツ",
    nameEn: "Fruits & Fruits Pancake",
    description: "季節のフレッシュフルーツをふんだんにトッピングした、目にも鮮やかな彩り豊かな一皿。旬の果物だけを厳選して使用しており、みずみずしい甘酸っぱさとふんわり生地の組み合わせが最高です。ホイップクリームとともに美しく盛り付けられており、見た目の美しさも食の喜びのひとつ。インスタ映えも抜群の人気メニューです。",
    price: 1485,
    image: LOCAL.p2,
    tag: "おすすめ",
  },

  // ─── FRENCH TOAST ────────────────────────────────────────
  {
    id: "ft1",
    category: "food",
    subcategory: "french_toast",
    name: "フレンチトースト",
    nameEn: "French Toast",
    description: "フランス産ブリオッシュを特製の卵液に一晩かけてじっくりと漬け込み、表面はカリッと中はとろりとした濃厚な味わいに焼き上げたフレンチトーストです。北海道産有機バターとカナダ産メープルシロップを添えて。卵の風味がたっぷりと染み込んだリッチな口当たりは、一度食べると忘れられない美味しさです。",
    price: 1045,
    image: LOCAL.ft1,
    tag: "人気",
  },
  {
    id: "ft2",
    category: "food",
    subcategory: "french_toast",
    name: "フレンチトースト フルーツ添え",
    nameEn: "French Toast with Fruits",
    description: "定番フレンチトーストに、旬のフレッシュフルーツを贅沢に添えた華やかな一皿。フランス産ブリオッシュを一晩漬け込んで焼き上げた濃厚なフレンチトーストに、旬のカラフルなフルーツの甘酸っぱさが加わることで、豊かな味わいの変化が生まれます。ホイップクリームとともに美しく盛り付けられており、見た目も華やかで特別な朝のひとときにぴったりです。",
    price: 1320,
    image: LOCAL.ft1,
  },

  // ─── EGGS BENEDICT ───────────────────────────────────────
  {
    id: "eb1",
    category: "food",
    subcategory: "eggs_benedict",
    name: "ベーコンとほうれん草",
    nameEn: "Bacon & Spinach Benedict",
    description: "YORKYSの人気ナンバー1エッグベネディクト。カナディアンベーコンのしっかりとした旨みと、鮮やかなほうれん草の風味が絶妙にマッチ。その上にのるポーチドエッグはとろりとした半熟仕立てで、割ると黄身がゆっくりと流れ出す贅沢な演出が楽しめます。バターとレモン風味の本格オランデーズソースをたっぷりかけてご提供します。",
    price: 1100,
    image: IMG.benedict,
    tag: "人気",
  },
  {
    id: "eb2",
    category: "food",
    subcategory: "eggs_benedict",
    name: "サーモンとアボカド",
    nameEn: "Salmon & Avocado Benedict",
    description: "スモークサーモンのなめらかな旨みと、クリーミーなアボカドの濃厚さが絶妙に調和したエッグベネディクト。とろりとした半熟のポーチドエッグを割ると黄身が流れ出し、手作りオランデーズソースとともに素材の美味しさが一体になります。彩り豊かで食べ応えも抜群。ブランチの定番として絶大な人気を誇るメニューです。",
    price: 1210,
    image: IMG.benedict2,
  },
  {
    id: "eb3",
    category: "food",
    subcategory: "eggs_benedict",
    name: "生ハムとクリームチーズ",
    nameEn: "Prosciutto & Cream Cheese Benedict",
    description: "薄切りにスライスした上質な生ハムと、なめらかなクリームチーズを組み合わせた贅沢なエッグベネディクト。塩味の効いた生ハムのコクとクリームチーズのマイルドな酸味が、本格オランデーズソースとともに口の中で絶妙に溶け合います。半熟に仕上げたポーチドエッグとともにいただく、特別感あふれる一皿です。",
    price: 1320,
    image: IMG.benedict,
  },

  // ─── EGG SANDWICH ────────────────────────────────────────
  {
    id: "s1",
    category: "food",
    subcategory: "sandwich",
    name: "オムレツたまごサンド プレーン",
    nameEn: "Omelette Egg Sandwich",
    description: "ふわとろに仕上げたオムレツと、YORKYSオリジナルの自家製マヨネーズをサンドした定番のたまごサンドです。卵の風味を最大限に引き出した、シンプルながらも奥深い美味しさが魅力。使用する卵は新鮮な国産卵を厳選し、毎朝丁寧に仕込んでいます。朝食やランチのお供に、飽きのこない安定の美味しさです。",
    price: 770,
    image: IMG.sandwich,
    tag: "人気",
  },
  {
    id: "s2",
    category: "food",
    subcategory: "sandwich",
    name: "オムレツたまごサンド 黒トリュフ風味",
    nameEn: "Omelette Egg Sandwich Truffle",
    description: "プレーンのたまごサンドに、高級食材の黒トリュフオイルを加えた芳醇でリッチな一品。ふわとろのオムレツに黒トリュフの深い香りが漂い、口の中でエレガントな味わいが広がります。自家製マヨネーズとの相性も抜群で、ワンランク上の贅沢なたまごサンドをお楽しみいただけます。特別な気分の日にぜひどうぞ。",
    price: 935,
    image: IMG.sandwich2,
    tag: "おすすめ",
  },

  // ─── FRITTER ─────────────────────────────────────────────
  {
    id: "fr1",
    category: "food",
    subcategory: "fritter",
    name: "フレンチフライ",
    nameEn: "French Fries",
    description: "毎日丁寧に仕込むYORKYSのフレンチフライ。北海道産じゃがいもをサクサクに揚げたシンプルなポテトフライは、外はカリッと中はホクホクの食感が自慢。塩加減も絶妙で、そのままでも十分美味しいですが、添付のケチャップとの相性も抜群です。パンケーキやバーガーのサイドとしても人気の定番メニューです。",
    price: 660,
    image: IMG.fritter,
  },
  {
    id: "fr2",
    category: "food",
    subcategory: "fritter",
    name: "黒トリュフ フレンチフライ",
    nameEn: "Black Truffle French Fries",
    description: "プレミアムな黒トリュフオイルをたっぷりと絡めた、香り豊かな贅沢フレンチフライ。北海道産じゃがいもをカリッと揚げたポテトに、黒トリュフの上品な香りが全体に広がり、口の中で贅沢な風味が楽しめます。パルメザンチーズをトッピングすることで、さらに深みのある味わいに。ちょっと贅沢なひとときにどうぞ。",
    price: 990,
    image: IMG.fritter2,
    tag: "おすすめ",
  },

  // ─── HAMBURGER ───────────────────────────────────────────
  {
    id: "b1",
    category: "food",
    subcategory: "burger",
    name: "YORKYS バーガー",
    nameEn: "YORKYS Burger",
    description: "YORKYSが誇るシグネチャーバーガー。厳選した国産牛のパテに、新鮮なレタス、完熟トマト、カリカリベーコン、そしてふわとろオムレツを重ねた、食べ応え満点の一皿です。特製ソースがすべての食材をひとつにまとめ、豊かな味わいを生み出します。サクサクのフレンチフライが付いて、大満足のボリュームです。",
    price: 1353,
    image: IMG.burger,
    tag: "人気",
  },
  {
    id: "b2",
    category: "food",
    subcategory: "burger",
    name: "スパイシーチキン＆アボカドバーガー",
    nameEn: "Spicy Chicken & Avocado Burger",
    description: "スパイシーな味付けのジューシーなチキンパテに、クリーミーなアボカド、とろけるチーズを合わせたバーガー。ピリッとした辛さとアボカドのマイルドな甘みが絶妙なコントラストを生み出します。新鮮なレタスと完熟トマトのシャキシャキ感も加わり、食べるたびに異なる食感と味わいが楽しめる個性的な一品。フレンチフライ付きです。",
    price: 1430,
    image: IMG.burger2,
  },
  {
    id: "b3",
    category: "food",
    subcategory: "burger",
    name: "タルタルフィッシュフライバーガー",
    nameEn: "Fish Fry Tartar Burger",
    description: "カリッと揚げた白身魚のフィッシュフライに、手作りタルタルソースをたっぷりと合わせた爽やかなバーガー。紫キャベツのシャキシャキとした食感と酸味がアクセントになり、さっぱりとした味わいに仕上げています。新鮮なレタスと完熟トマトも重ね、食べ応えも十分。フレンチフライ付きでご提供します。",
    price: 1430,
    image: IMG.burger,
  },

  // ─── LUNCH（11:00–17:00）────────────────────────────────
  {
    id: "l1",
    category: "food",
    subcategory: "lunch",
    name: "ガーリックシュリンプのココナッツミルクカレー",
    nameEn: "Garlic Shrimp Coconut Curry",
    description: "プリプリのガーリックシュリンプが主役のスパイシーなカレー。ココナッツミルクのまろやかなコクと、複数のスパイスを絶妙にブレンドしたカレーペーストの深い辛みが融合し、エスニックな風味が広がります。ご飯との相性も抜群で、食欲を刺激する香り豊かな一皿。ランチの人気ナンバー1メニューです。",
    price: 1320,
    image: IMG.curry,
    tag: "人気",
  },
  {
    id: "l2",
    category: "food",
    subcategory: "lunch",
    name: "サワラの西京焼き",
    nameEn: "Grilled Saikyo Sawara",
    description: "白みそをベースにした西京みそに丁寧に漬け込んだサワラを、じっくりと焼き上げた上品な和の一皿。西京みその甘みとコクがサワラに深く染み込み、外はこんがり、中はふっくらとやわらかな仕上がりです。付け合わせのご飯とともにいただく、日本の伝統的な美味しさを大切にしたランチメニューです。",
    price: 1320,
    image: IMG.fish,
    tag: "おすすめ",
  },
  {
    id: "l3",
    category: "food",
    subcategory: "lunch",
    name: "イワシの柔らか煮",
    nameEn: "Braised Sardine",
    description: "骨まで柔らかくなるまでじっくりと時間をかけて煮込んだ、職人技のイワシの煮付け。醤油、みりん、砂糖をベースにしたやや甘辛な味付けが、イワシ特有の旨みと相まって深い味わいを生み出します。ご飯との相性は抜群で、心まで温まる家庭的なランチです。栄養豊富なイワシを美味しくいただけます。",
    price: 1320,
    image: IMG.fish,
  },
  {
    id: "l4",
    category: "food",
    subcategory: "lunch",
    name: "甘辛ヤンニョムチキン",
    nameEn: "Yangnyeom Chicken",
    description: "韓国発祥のヤンニョムダレをたっぷりと絡めた、甘さと辛さのバランスが絶妙なジューシーなチキンです。コチュジャンベースのタレが食欲をそそり、一度食べるとクセになる美味しさ。自家製タルタルソースを添えてご提供し、辛みとまろやかさのコントラストが楽しめます。ご飯との相性も抜群のランチメニューです。",
    price: 1320,
    image: IMG.chicken,
  },
  {
    id: "l5",
    category: "food",
    subcategory: "lunch",
    name: "オムライス ミニサラダセット",
    nameEn: "Omurice Salad Set",
    description: "夙川本店限定の特別メニュー。ふわとろに仕上げた薄焼き卵をたっぷりのチキンライスに包んだオムライスに、ミニサラダがセットになっています。ケチャップベースのチキンライスと、やさしい味付けの卵の組み合わせは定番中の定番。心温まる懐かしい味わいを、本店でしか味わえない特別な一皿です。",
    price: 1320,
    image: IMG.omelet,
    tag: "限定",
  },
  {
    id: "l6",
    category: "food",
    subcategory: "lunch",
    name: "彩り野菜のガパオライス",
    nameEn: "Gapao Rice",
    description: "タイ料理の定番「ガパオライス」をYORKYS流にアレンジした彩り豊かな一皿。赤・黄のパプリカ、ズッキーニなどカラフルな野菜と、香り高いホーリーバジルを使用し、ナンプラーベースの特製ソースで炒め合わせました。半熟の目玉焼きとともにいただく、エスニック風味のランチメニューです。",
    price: 1320,
    image: IMG.rice,
  },
  {
    id: "l7",
    category: "food",
    subcategory: "lunch",
    name: "淡路産牛ハンバーグステーキ",
    nameEn: "Awaji Beef Hamburg Steak",
    description: "兵庫県淡路島産の上質な牛肉を粗挽きにしたジューシーなハンバーグ。旨みたっぷりの肉汁が口の中に広がり、食べ応え十分な一皿です。長時間煮込んで深いコクを引き出した特製デミグラスソースをかけてご提供。付け合わせの野菜とともに、贅沢なランチタイムをお楽しみください。ご飯との相性も抜群です。",
    price: 1540,
    image: IMG.hamburg,
    tag: "おすすめ",
  },
  {
    id: "l8",
    category: "food",
    subcategory: "lunch",
    name: "おむたらパスタ パンセット",
    nameEn: "Omu Tara Pasta & Bread",
    description: "タラコのほど良い塩気とプチプチとした食感が楽しい和風パスタ。その上にふわとろのスクランブルエッグをのせた、YORKYSオリジナルの「おむたら」スタイルでご提供します。バターとクリームで仕上げた濃厚な味わいは、一度食べると忘れられない美味しさ。パンとのセットでご提供します。",
    price: 1320,
    image: IMG.pasta,
  },
  {
    id: "l9",
    category: "food",
    subcategory: "lunch",
    name: "ぺぺたまパスタ パンセット",
    nameEn: "Pepe Tama Pasta & Bread",
    description: "シンプルながら奥深い味わいのペペロンチーノに、とろとろの卵黄をのせた贅沢な一皿。ガーリックとペペロンの刺激的な辛みと香りが食欲をそそり、卵黄のコクがそれをやさしく包み込む絶妙な組み合わせです。厳選したオリーブオイルとともに仕上げた、素材の美味しさが光るパスタです。パンセット付き。",
    price: 1210,
    image: IMG.pasta,
  },
  {
    id: "l10",
    category: "food",
    subcategory: "lunch",
    name: "グリルチキン バジルサラダ パンセット",
    nameEn: "Grilled Chicken Basil Salad & Bread",
    description: "ハーブを使って香り高くグリルしたチキンに、フレッシュバジルをたっぷりと使った特製ドレッシングを合わせたボリューム満点のサラダプレートです。野菜本来の甘みと、バジルの爽やかな香りが相まって、軽やかでさっぱりとした味わいに仕上がっています。ヘルシーに食べたい方におすすめ。パンセット付き。",
    price: 1210,
    image: IMG.salad,
  },
  {
    id: "l11",
    category: "food",
    subcategory: "lunch",
    name: "ガーリックシュリンプ＆アボカドサラダ パンセット",
    nameEn: "Garlic Shrimp & Avocado Caesar Salad & Bread",
    description: "プリプリのガーリックシュリンプとクリーミーなアボカドをたっぷりと使ったシーザードレッシングのサラダプレートです。ニンニクの香ばしさとシュリンプの旨み、アボカドのまろやかなコクが三位一体となった満足感の高い一皿。シーザードレッシングが全体をまとめ上げ、食べ応えも抜群。パンセット付きです。",
    price: 1210,
    image: IMG.salad,
  },
  {
    id: "l12",
    category: "food",
    subcategory: "lunch",
    name: "ミニパンケーキ",
    nameEn: "Mini Pancake",
    description: "ランチの最後を締めくくる、かわいいミニサイズのパンケーキ。YORKYSの定番パンケーキと同じ生地を使い、ひとくちサイズに焼き上げました。メープルシロップと有機バターを添えてご提供。デザートとしてはもちろん、サイドメニューとしてもご活用いただけます。甘いものでランチをしめくくりましょう。",
    price: 440,
    image: LOCAL.p1,
  },

  // ─── COFFEE ──────────────────────────────────────────────
  {
    id: "c1",
    category: "drink",
    subcategory: "coffee",
    name: "ブレンドコーヒー",
    nameEn: "Blend Coffee",
    description: "YORKYSが厳選した豆をオリジナルブレンドしてドリップしたコーヒーです。複数の産地の豆を丁寧にブレンドすることで、バランスの良い香りと味わいを実現。酸味と苦みが絶妙に調和したまろやかな口当たりが特徴で、食事の後にゆっくりとお楽しみいただけます。コーヒー本来の風味をシンプルにご堪能ください。",
    price: 462,
    image: LOCAL.c1,
  },
  {
    id: "c2",
    category: "drink",
    subcategory: "coffee",
    name: "アイスコーヒー",
    nameEn: "Iced Coffee",
    description: "深煎りの豆を使ったすっきりとしたアイスコーヒー。氷で急冷することでコーヒー本来の風味と深いコクをそのまま閉じ込め、ぼかのない爽快な味わいに仕上げています。暑い日のブランチや、食後のリフレッシュに最適。ミルクを加えてアイスカフェオレとしても楽しめます。",
    price: 495,
    image: IMG.icecoffee,
  },
  {
    id: "c3",
    category: "drink",
    subcategory: "coffee",
    name: "カフェオレ",
    nameEn: "Café au Lait",
    description: "YORKYSオリジナルブレンドのコーヒーと、なめらかなスチームミルクを同量ずつ合わせたまろやかなカフェオレ。コーヒーの香り豊かな苦みとミルクのやさしい甘みが一体となり、心地よいバランスの一杯に仕上がっています。HOTとICEからお選びいただけます。ゆったりとしたブランチのひとときに。",
    price: 550,
    image: IMG.latte,
  },
  {
    id: "c4",
    category: "drink",
    subcategory: "coffee",
    name: "エスプレッソ",
    nameEn: "Espresso",
    description: "厳選したアラビカ種の豆を高圧で抽出した、濃厚でコクのある本格エスプレッソ。短時間で抽出することで、コーヒーの旨みと複雑な風味が凝縮されています。その濃厚さの中にほのかな甘みがあり、食後のリセットに最適な一杯。コーヒー好きにこそぜひ試していただきたい本格的な一杯です。",
    price: 407,
    image: LOCAL.c1,
  },
  {
    id: "c5",
    category: "drink",
    subcategory: "coffee",
    name: "カフェラテ",
    nameEn: "Café Latte",
    description: "エスプレッソの濃厚な香りとスチームミルクのやさしいコクが調和した、YORKYSで最も人気のコーヒードリンク。なめらかなミルクフォームが表面を覆い、口当たりはまろやかで飲みやすい一杯です。HOTとICEからお選びいただけます。バリスタがひとつひとつ丁寧に作るラテアートもお楽しみに。",
    price: 550,
    image: LOCAL.c2,
    tag: "人気",
  },
  {
    id: "c6",
    category: "drink",
    subcategory: "coffee",
    name: "ヘーゼルナッツラテ",
    nameEn: "Hazelnut Latte",
    description: "ヘーゼルナッツシロップの香ばしく甘い香りと、エスプレッソのコクが融合した風味豊かなラテ。ナッツの自然な甘みがミルクのまろやかさをより一層引き立て、リッチで心地よい味わいを生み出します。甘いものが好きな方にも、コーヒーが好きな方にも満足いただける一杯です。HOTとICEでどうぞ。",
    price: 660,
    image: IMG.latte,
  },
  {
    id: "c7",
    category: "drink",
    subcategory: "coffee",
    name: "バニララテ",
    nameEn: "Vanilla Latte",
    description: "マダガスカル産の最高品質のバニラを使ったシロップで風味付けした、やさしい甘さのバニララテ。バニラ特有の甘くスイートな香りとエスプレッソのほろ苦さが絶妙なバランスで、飲むたびに幸福感に包まれる一杯です。スイーツのような豊かな風味は、ゆったりとしたカフェタイムのお供に最適。HOTとICEでどうぞ。",
    price: 660,
    image: IMG.latte,
  },
  {
    id: "c8",
    category: "drink",
    subcategory: "coffee",
    name: "キャラメルラテ",
    nameEn: "Caramel Latte",
    description: "自家製のリッチなキャラメルソースをたっぷりと使ったキャラメルラテ。砂糖をじっくりと煮詰めたキャラメルの深いコクとほろ苦さが、エスプレッソの旨みとミルクのまろやかさと融合し、濃厚で贅沢な味わいを生み出します。甘いもの好きに特に人気のメニューです。HOTとICEでお楽しみいただけます。",
    price: 660,
    image: IMG.latte,
  },
  {
    id: "c9",
    category: "drink",
    subcategory: "coffee",
    name: "モカラテ",
    nameEn: "Mocha Latte",
    description: "上質なチョコレートシロップとエスプレッソ、スチームミルクを合わせた甘くリッチなモカラテ。チョコレートのほのかな甘みと苦みがエスプレッソの風味と一体となり、デザートのような豊かな味わいを演出します。チョコレート好き、コーヒー好き、どちらにもおすすめの人気メニューです。HOT・ICEでどうぞ。",
    price: 660,
    image: IMG.latte,
  },
  {
    id: "c10",
    category: "drink",
    subcategory: "coffee",
    name: "カプチーノ",
    nameEn: "Cappuccino",
    description: "バリスタが丁寧に作り上げるふわふわのミルクフォームと、濃厚なエスプレッソのバランスが絶妙なカプチーノ。きめ細かいフォームがエスプレッソの苦みをやさしく包み込み、口に含むと豊かな香りが広がります。表面に描かれたラテアートも見どころのひとつ。本格的なイタリアンカフェ体験をお楽しみください。",
    price: 594,
    image: LOCAL.c3,
  },
  {
    id: "c11",
    category: "drink",
    subcategory: "coffee",
    name: "ココア",
    nameEn: "Hot Cocoa",
    description: "上質なカカオを使ったまろやかなホットチョコレートドリンク。チョコレートの深いコクと甘みが口いっぱいに広がり、心も体も温まる一杯です。アイスでもご提供可能で、暑い季節には冷たくても楽しめます。お子様から大人まで楽しめる定番の人気ドリンク。ふわふわのミルクフォームを添えてご提供します。",
    price: 616,
    image: IMG.cocoa,
  },
  {
    id: "c12",
    category: "drink",
    subcategory: "coffee",
    name: "ミルク",
    nameEn: "Milk",
    description: "地元の牧場から仕入れた新鮮な牛乳をそのままお楽しみいただけるシンプルなミルク。余計なものを一切加えず、素材そのものの自然な甘みとコクをご堪能ください。HOTでお召し上がりの場合は、ほんのり温めてご提供します。お子様やミルク好きの方に喜ばれる、体にやさしいメニューです。",
    price: 407,
    image: IMG.milk,
  },

  // ─── TEA ─────────────────────────────────────────────────
  {
    id: "t1",
    category: "drink",
    subcategory: "tea",
    name: "アールグレイ",
    nameEn: "Earl Grey",
    description: "上質な茶葉を使ったアールグレイ。ベルガモットの柑橘系の香りが豊かに立ち上り、爽やかな気分にさせてくれる一杯です。すっきりとした味わいの中に、紅茶本来のまろやかな渋みが絶妙なバランスで調和。ミルクを加えてアールグレイミルクティーとしてもお楽しみいただけます。HOTでご提供します。",
    price: 495,
    image: IMG.tea,
  },
  {
    id: "t2",
    category: "drink",
    subcategory: "tea",
    name: "アッサム",
    nameEn: "Assam",
    description: "インド・アッサム地方産の茶葉を使った、コクと渋みのバランスが絶妙な本格的な紅茶。力強い風味と深い赤色が特徴的で、ミルクとの相性が抜群です。ミルクティーにすることでさらにまろやかさが加わり、飲みやすくなります。食事の後にゆっくりとお楽しみいただくのがおすすめです。HOTでご提供します。",
    price: 495,
    image: IMG.tea,
  },
  {
    id: "t3",
    category: "drink",
    subcategory: "tea",
    name: "ダージリン",
    nameEn: "Darjeeling",
    description: "「紅茶のシャンパン」と称される世界最高品質のダージリン茶葉を使用した一杯。インド・ダージリン地方の標高の高い茶園で育てられた繊細な茶葉は、マスカットのような独特のフルーティーな香りが特徴です。透き通った美しいオレンジ色のお茶は、ストレートでお楽しみください。HOTでご提供します。",
    price: 495,
    image: IMG.tea,
  },
  {
    id: "t4",
    category: "drink",
    subcategory: "tea",
    name: "アイスティー",
    nameEn: "Iced Tea",
    description: "YORKYSオリジナルブレンドの紅茶を丁寧に抽出し、氷で急冷したすっきりとしたアイスティー。茶葉本来の風味と爽やかな後味が特徴で、暑い季節に特に人気のドリンクです。ほんのりとした甘みとキレのある後味で、食中や食後のリフレッシュにもぴったり。レモンを添えてご提供します。",
    price: 506,
    image: IMG.tea,
  },
  {
    id: "t5",
    category: "drink",
    subcategory: "tea",
    name: "ロイヤルミルクティー",
    nameEn: "Royal Milk Tea",
    description: "上質なアッサム茶葉をミルクでじっくりと煮出した、深いコクとまろやかさが自慢のロイヤルミルクティー。砂糖なしでも茶葉の自然な甘みとミルクのコクが感じられる贅沢な一杯です。英国式の本格的な製法で仕上げた濃厚な味わいは、一度飲んだら忘れられない美味しさ。HOTとICEからお選びください。",
    price: 550,
    image: IMG.tea,
    tag: "人気",
  },
  {
    id: "t6",
    category: "drink",
    subcategory: "tea",
    name: "ハニーロイヤルミルクティー",
    nameEn: "Honey Royal Milk Tea",
    description: "ロイヤルミルクティーに国産の天然はちみつをたっぷりと加えた、やさしく甘い特別な一杯。アッサム茶葉の豊かなコクとはちみつの自然な甘みが溶け合い、心も体もほっとリラックスできる温かみのある味わいです。少し疲れた時や、甘いものでほっと一息つきたい時に最適。HOTとICEでどうぞ。",
    price: 660,
    image: IMG.tea,
  },

  // ─── SOFT DRINK ──────────────────────────────────────────
  {
    id: "sd1",
    category: "drink",
    subcategory: "soft",
    name: "オレンジジュース",
    nameEn: "Orange Juice",
    description: "厳選したオレンジを丁寧に搾ったフレッシュなオレンジジュース。人工添加物を一切使用せず、果実本来の甘みと酸味、みずみずしさをそのままお届けします。朝のブランチのお供に最適で、フルーティーな香りと爽やかな後味が気分をリフレッシュさせてくれます。ビタミンCも豊富で体にもやさしい一杯です。",
    price: 462,
    image: IMG.juice,
  },
  {
    id: "sd2",
    category: "drink",
    subcategory: "soft",
    name: "グレープフルーツジュース",
    nameEn: "Grapefruit Juice",
    description: "搾りたての新鮮なグレープフルーツを使用した、爽やかな酸味とほのかな苦みが特徴のジュース。甘さ控えめのさっぱりとした後味が、食事の合間や食後のリフレッシュにぴったりです。人工甘味料や添加物は一切使用せず、果実本来の風味をそのままお楽しみいただけます。ビタミンCも豊富な一杯です。",
    price: 462,
    image: IMG.juice,
  },
  {
    id: "sd3",
    category: "drink",
    subcategory: "soft",
    name: "アップルジュース",
    nameEn: "Apple Juice",
    description: "厳選したリンゴを丁寧に搾ったまろやかな甘みのアップルジュース。リンゴ特有のフルーティーな香りと自然な甘さが楽しめる、子供から大人まで人気のドリンクです。人工甘味料や添加物を使用せず、果実本来の美味しさをそのままお届けします。さっぱりとした後味で、食事の合間にもぴったりです。",
    price: 462,
    image: IMG.juice,
  },
  {
    id: "sd4",
    category: "drink",
    subcategory: "soft",
    name: "ジンジャーエール",
    nameEn: "Ginger Ale",
    description: "甘口と辛口からお選びいただける本格ジンジャーエール。生姜の自然な辛みと炭酸の爽快な刺激が口の中に広がり、食欲増進や気分転換に最適な一杯です。甘口はまろやかな甘みと生姜の香りが楽しめ、辛口はよりシャープでスパイシーな味わいが特徴。食事の合間に最適です。",
    price: 462,
    image: IMG.juice,
  },
  {
    id: "sd5",
    category: "drink",
    subcategory: "soft",
    name: "コカコーラ",
    nameEn: "Coca-Cola",
    description: "世界中で愛されている定番の炭酸飲料コカコーラ。独特の甘みとスパイス感のある複雑な味わい、そして爽快な炭酸の刺激が食欲を刺激します。フレッシュな氷とともにグラスでご提供。バーガーやフレンチフライとの相性は言わずもがな、食事をより一層楽しくしてくれるドリンクです。お食事のお供にぜひどうぞ。",
    price: 462,
    image: IMG.juice,
  },
  {
    id: "sd6",
    category: "drink",
    subcategory: "soft",
    name: "スパークリングミネラルウォーター",
    nameEn: "Perrier",
    description: "フランス生まれの天然炭酸水ペリエを使用したスパークリングミネラルウォーター。自然の炭酸が適度に含まれており、爽快な飲み口が特徴です。食事の味をリセットしてくれる効果もあり、料理との相性は特に抜群。人工甘味料は一切不使用で、ミネラル豊富な天然水をそのままお楽しみいただけます。",
    price: 550,
    image: IMG.juice,
  },
  {
    id: "sd7",
    category: "drink",
    subcategory: "soft",
    name: "ウーロン茶",
    nameEn: "Oolong Tea",
    description: "中国茶の中でも特に人気の高い烏龍茶。発酵度合いが緑茶と紅茶の中間で、独特の爽やかな香りと渋みのないすっきりとした飲み口が特徴です。食事中のお供として最適で、口の中をさっぱりとリセットしてくれます。カフェインも適度に含まれており、リフレッシュしたい時にもぴったりの一杯です。",
    price: 407,
    image: IMG.tea,
  },

  // ─── ALCOHOL — BEER ──────────────────────────────────────
  {
    id: "a1",
    category: "drink",
    subcategory: "alcohol",
    name: "ギネス（黒）",
    nameEn: "Guinness",
    description: "アイルランドを代表する世界的に有名な黒ビール、ギネス。滑らかでクリーミーな泡と、ローストした麦芽の深いコクとほろ苦さが特徴的な一杯です。ナイトロジェンガスを使って注ぐことで生まれる独特のきめ細かい泡が長続きし、最後まで美味しく楽しめます。ビールとは思えないほどまろやかな口当たりです。",
    price: 616,
    image: IMG.beer,
    tag: "人気",
  },
  {
    id: "a2",
    category: "drink",
    subcategory: "alcohol",
    name: "コロナ",
    nameEn: "Corona",
    description: "メキシコ生まれの世界的人気ビール、コロナエクストラ。軽やかな飲み口とほのかな甘みが特徴の、すっきりとしたラガービールです。ライムを絞ってボトルの口に入れてお楽しみいただくのがメキシカンスタイル。爽やかな柑橘の酸味がビールの甘みとマッチし、暑い日や食前のアペタイザーとして特に人気の一杯です。",
    price: 616,
    image: IMG.beer,
  },
  {
    id: "a3",
    category: "drink",
    subcategory: "alcohol",
    name: "ハイネケン",
    nameEn: "Heineken",
    description: "オランダ生まれの世界的に有名なプレミアムビール、ハイネケン。厳選されたホップと天然水を使用した、フルーティーな香りとすっきりとした後味が特徴のラガービールです。鮮やかな緑のボトルで世界中に知られるブランドの本格的な味わいをYORKYSでお楽しみください。バーガーやフライとの相性も抜群です。",
    price: 616,
    image: IMG.beer,
  },
  {
    id: "a4",
    category: "drink",
    subcategory: "alcohol",
    name: "キリン ゼロイチ（ノンアルコール）",
    nameEn: "Kirin Zero Ichi",
    description: "アルコールを一切含まない、本格的な味わいのノンアルコールビール。キリンが丁寧に作り上げたゼロイチは、ビール特有の深いコクと爽快な飲み口を実現しながら、アルコール分は0.00%。妊娠中の方やお車でのご来店の方も安心してお楽しみいただける一杯です。ビールと同じ感覚で楽しめます。",
    price: 616,
    image: IMG.beer,
  },

  // ─── ALCOHOL — COCKTAIL ──────────────────────────────────
  {
    id: "a5",
    category: "drink",
    subcategory: "alcohol",
    name: "カシス",
    nameEn: "Cassis",
    description: "フランス産ブラックカラントを使ったリキュール「カシス」。鮮やかな紫色と濃厚なベリーの甘みが特徴的で、ソーダで割ったカシスソーダや、オレンジジュースで割ったカシスオレンジなど、お好みのドリンクで割ってお楽しみいただけます。フルーティーで飲みやすく、特に女性に人気のリキュールです。",
    price: 759,
    image: IMG.cocktail,
  },
  {
    id: "a6",
    category: "drink",
    subcategory: "alcohol",
    name: "カンパリ",
    nameEn: "Campari",
    description: "イタリア生まれの鮮やかな赤色のビタースピリッツ。オレンジの皮や様々なハーブ・スパイスを使ったユニークな苦みと甘みのバランスが特徴です。ソーダで割ったカンパリソーダはすっきりとした飲み口で食前酒として最適。オレンジジュースとの組み合わせも人気で、大人の味わいが楽しめます。",
    price: 759,
    image: IMG.cocktail,
  },
  {
    id: "a7",
    category: "drink",
    subcategory: "alcohol",
    name: "ライチ",
    nameEn: "Lychee",
    description: "中国南部原産のエキゾチックなフルーツ「ライチ」をベースにした甘くフルーティーなリキュール。華やかな香りとみずみずしい甘みが特徴で、ソーダで割ってさっぱりと、または炭酸で割って爽快にお楽しみいただけます。飲みやすく甘いので、お酒が得意でない方にも人気の一杯です。",
    price: 759,
    image: IMG.cocktail,
  },
  {
    id: "a8",
    category: "drink",
    subcategory: "alcohol",
    name: "ピーチ",
    nameEn: "Peach",
    description: "新鮮な桃の甘くジューシーな香りと味わいが楽しめるピーチリキュール。ソーダで割ったピーチソーダや、オレンジジュースで割ったファジーネーブルなど、様々な飲み方でお楽しみいただけます。甘みが強く飲みやすいため、お酒が初めての方やカクテルが好きな方にも特におすすめの一杯です。",
    price: 759,
    image: IMG.cocktail,
  },
  {
    id: "a9",
    category: "drink",
    subcategory: "alcohol",
    name: "ジン",
    nameEn: "Gin",
    description: "ジュニパーベリーを主体に多種のボタニカルを加えたプレミアムジン。爽やかな松の香りと複雑なスパイス感が特徴で、トニックウォーターで割ったジントニックが定番の楽しみ方です。氷を入れたグラスにジンを注ぎ、トニックをゆっくり注ぐだけで本格的なカクテルが完成。カットライムを添えてお楽しみください。",
    price: 759,
    image: IMG.cocktail,
  },
  {
    id: "a10",
    category: "drink",
    subcategory: "alcohol",
    name: "ウォッカ",
    nameEn: "Vodka",
    description: "蒸留を繰り返すことで生まれる、限りなくクリアでピュアな味わいのウォッカ。その無色透明なクリーンさが様々なドリンクと相性抜群で、ソーダで割ってウォッカソーダに、または好みのジュースで割ってお楽しみください。アルコール度数が高めのため、ゆっくりとお召し上がりいただくことをおすすめします。",
    price: 759,
    image: IMG.cocktail,
  },
  {
    id: "a11",
    category: "drink",
    subcategory: "alcohol",
    name: "ウイスキー",
    nameEn: "Whisky",
    description: "豊かな香りと深い味わいが魅力のウイスキー。樽で熟成させることで生まれる複雑なフレーバーとアルコールの温かい余韻が特徴です。ソーダで割ったハイボールでさっぱりと、または水割りでまろやかに、あるいはストレートで本来の風味をお楽しみください。大人の一杯として特に人気のスピリッツです。",
    price: 759,
    image: IMG.cocktail,
  },

  // ─── ALCOHOL — WINE COCKTAIL ─────────────────────────────
  {
    id: "a12",
    category: "drink",
    subcategory: "alcohol",
    name: "スプリッツァー",
    nameEn: "Spritzer",
    description: "ソーダで割った白ワインのイタリアンスタイルカクテル、スプリッツァー。白ワインのフルーティーな風味と炭酸の爽快な刺激が組み合わさり、すっきりとした軽やかな飲み口が特徴です。アルコール度数が低めなので飲みやすく、食前や食中酒として最適。食事を邪魔しない上品な味わいです。",
    price: 814,
    image: IMG.cocktail,
    tag: "おすすめ",
  },
  {
    id: "a13",
    category: "drink",
    subcategory: "alcohol",
    name: "オペレーター",
    nameEn: "Operator",
    description: "ジンジャーエールで白ワインを割った、軽やかでさっぱりとしたワインカクテル。生姜のスパイシーな刺激と白ワインのフルーティーな香りが絶妙にマッチ。アルコール度数が控えめで飲みやすく、食事の合間に楽しめる爽やかな一杯です。炭酸の爽快感とワインの風味を同時に楽しめます。",
    price: 814,
    image: IMG.cocktail,
  },
  {
    id: "a14",
    category: "drink",
    subcategory: "alcohol",
    name: "キール",
    nameEn: "Kir",
    description: "フランス・ブルゴーニュ地方発祥の定番カクテル。白ワインにカシスリキュールを加えた、鮮やかな赤紫色が美しい一杯です。カシスのベリーの甘みと白ワインの酸味が絶妙に調和し、食前酒として最適な華やかな味わいを演出します。見た目も美しく、特別な日の乾杯にぴったりのカクテルです。",
    price: 814,
    image: IMG.cocktail,
  },
  {
    id: "a15",
    category: "drink",
    subcategory: "alcohol",
    name: "キティ",
    nameEn: "Kitty",
    description: "ジンジャーエールで赤ワインを割った、甘みとスパイシーさが楽しいカクテル。赤ワインの深いコクとフルーティーな風味に、ジンジャーエールの爽快な炭酸と生姜の辛みが加わり、複雑で飲み応えのある味わいに仕上がっています。アルコール度数も控えめで飲みやすく、食事に合わせやすい一杯です。",
    price: 814,
    image: IMG.cocktail,
  },
  {
    id: "a16",
    category: "drink",
    subcategory: "alcohol",
    name: "カリモーチョ",
    nameEn: "Kalimotxo",
    description: "スペインのバスク地方発祥のユニークなカクテル。コーラの甘みとスパイス感に、赤ワインの深いコクと渋みが加わったクセになる味わいです。若者を中心に世界的に人気が広がっているトレンドカクテルで、初めての方も一度お試しいただけると新たな発見があるかもしれません。ユニークな組み合わせをお楽しみください。",
    price: 814,
    image: IMG.cocktail,
  },
  {
    id: "a17",
    category: "drink",
    subcategory: "alcohol",
    name: "ミモザ",
    nameEn: "Mimosa",
    description: "フレッシュなオレンジジュースとスパークリングワインを合わせた、朝食やブランチの定番カクテル、ミモザ。黄色い花の名前を冠した華やかな色合いと、柑橘の爽やかな香りが特徴です。オレンジジュースの甘みと酸味、スパークリングワインの軽やかな泡立ちが完璧なバランス。特別な朝のひとときに最適です。",
    price: 913,
    image: IMG.sparkling,
  },
  {
    id: "a18",
    category: "drink",
    subcategory: "alcohol",
    name: "キールロワイヤル",
    nameEn: "Kir Royal",
    description: "フランス・ブルゴーニュの定番カクテル「キール」のスパークリングワイン版。スパークリングワインにカシスリキュールを加えた、華やかな泡と鮮やかな赤紫色が美しい贅沢な一杯です。特別な日の乾杯やお祝いのシーンにぴったり。泡の心地よい刺激とカシスの甘みが口の中で弾けます。",
    price: 913,
    image: IMG.sparkling,
  },

  // ─── ALCOHOL — SPARKLING WINE ────────────────────────────
  {
    id: "a19",
    category: "drink",
    subcategory: "alcohol",
    name: "フィオーレ・デル・アモーレ グラス",
    nameEn: "Fiore dell'Amore (Glass)",
    description: "イタリア語で「愛の花」を意味するフィオーレ・デル・アモーレ。イタリア産の辛口スパークリングワインをグラスでご提供しています。繊細な泡立ちと爽やかな酸味、フルーティーな香りが特徴で、食前のアペロや食中酒として最適。特別なひとときを彩る、おすすめのスパークリングワインです。",
    price: 880,
    image: IMG.sparkling,
    tag: "おすすめ",
  },
  {
    id: "a20",
    category: "drink",
    subcategory: "alcohol",
    name: "フィオーレ・デル・アモーレ ボトル",
    nameEn: "Fiore dell'Amore (Bottle)",
    description: "イタリア産辛口スパークリングワイン「フィオーレ・デル・アモーレ」のボトルサービスです。繊細な泡立ちと爽やかな酸味、フルーティーな香りが楽しめるスパークリングワインをボトルでお楽しみください。グループでのお祝いや特別なランチ・ディナーシーンを華やかに彩る一本です。",
    price: 3300,
    image: IMG.sparkling,
  },
  {
    id: "a21",
    category: "drink",
    subcategory: "alcohol",
    name: "サンテロ 天使のアスティ ボトル",
    nameEn: "Santero Asti (Bottle)",
    description: "イタリア・ピエモンテ州産のマスカット葡萄を使った甘口スパークリングワイン「天使のアスティ」。フルーティーで甘みが強く、スパークリングワインが初めての方にも飲みやすい一本です。記念日や特別なお祝いのシーンに、グループみんなで楽しんでいただけるボトルサービスです。",
    price: 3300,
    image: IMG.sparkling,
  },

  // ─── ALCOHOL — RED WINE ──────────────────────────────────
  {
    id: "a22",
    category: "drink",
    subcategory: "alcohol",
    name: "赤ワイン グラス",
    nameEn: "Red Wine (Glass)",
    description: "フランスの名門ワイナリー「ミッシェル・シャプティエ」が手掛ける赤ワインをグラスでご提供。南フランス産の葡萄から作られる、果実味にあふれたフレッシュで飲みやすいミディアムボディが特徴です。赤い果実や温かいスパイスのニュアンスが感じられ、YORKYSの料理との相性も抜群です。",
    price: 649,
    image: IMG.wine,
  },
  {
    id: "a23",
    category: "drink",
    subcategory: "alcohol",
    name: "赤ワイン ボトル ミッシェル・シャプティエ",
    nameEn: "Red Wine Bottle — M. Chapoutier",
    description: "フランスの名門「ミッシェル・シャプティエ」が手掛ける赤ワインのボトルサービス。南フランスを代表する葡萄品種から丁寧に作られた、果実味豊かでフレッシュなミディアムボディです。飲みやすく料理を選ばない万能ワインで、グループでのランチやディナーにぴったりの一本です。",
    price: 3025,
    image: IMG.wine,
  },
  {
    id: "a24",
    category: "drink",
    subcategory: "alcohol",
    name: "赤ワイン ボトル フレンチドッグ メルロー",
    nameEn: "Red Wine Bottle — French Dog Merlot",
    description: "フランス産メルロー種を中心に使ったリッチで滑らかな口当たりの赤ワイン。チョコレートやバニラ、熟した赤い果実の豊かな香りと、なめらかなタンニンが特徴的なフルボディワインです。牛ハンバーグやチーズとの相性が特に良く、食事をより一層引き立てる一本。大切な方と特別なひとときをどうぞ。",
    price: 3600,
    image: IMG.wine,
  },

  // ─── ALCOHOL — WHITE WINE ────────────────────────────────
  {
    id: "a25",
    category: "drink",
    subcategory: "alcohol",
    name: "白ワイン グラス",
    nameEn: "White Wine (Glass)",
    description: "フランスの名門「ミッシェル・シャプティエ」が手掛ける白ワインをグラスでご提供。ピーチや柑橘など白い果実の豊かな香りと、フルーティーで爽やかな酸味が特徴的な飲みやすい一杯です。生ハムやサーモン、鶏料理など様々な食材と相性が良く、ランチやディナーのお供にぴったりです。",
    price: 649,
    image: IMG.wine,
  },
  {
    id: "a26",
    category: "drink",
    subcategory: "alcohol",
    name: "白ワイン ボトル ミッシェル・シャプティエ",
    nameEn: "White Wine Bottle — M. Chapoutier",
    description: "フランスの名門「ミッシェル・シャプティエ」が手掛ける白ワインのボトルサービス。ピーチや柑橘など白い果実の豊かな香りと、きりっとしたフルーティーな酸味の辛口。すっきりとしたキレのある後味が食欲を刺激し、YORKYSのお料理と抜群の相性を誇ります。グループでお楽しみください。",
    price: 3025,
    image: IMG.wine,
  },
  {
    id: "a27",
    category: "drink",
    subcategory: "alcohol",
    name: "白ワイン ボトル フレンチドッグ",
    nameEn: "White Wine Bottle — French Dog",
    description: "フランスのコロンバール種とシャルドネ種をブレンドした、個性豊かな辛口白ワイン。柑橘やパイナップルなどトロピカルフルーツの華やかな香りが特徴で、さっぱりとした後味が食中酒として最適です。魚介料理やサラダとの相性が抜群で、特別な食事の場を彩る一本です。",
    price: 3600,
    image: IMG.wine,
  },
];

export const foodSubcategories: { key: FoodSubcategory; label: string }[] = [
  { key: "pancake",       label: "パンケーキ" },
  { key: "french_toast",  label: "フレンチトースト" },
  { key: "eggs_benedict", label: "エッグベネディクト" },
  { key: "sandwich",      label: "サンドイッチ" },
  { key: "fritter",       label: "フリッター" },
  { key: "burger",        label: "バーガー" },
  { key: "lunch",         label: "ランチ" },
];

export const drinkSubcategories: { key: DrinkSubcategory; label: string }[] = [
  { key: "coffee",  label: "コーヒー" },
  { key: "tea",     label: "紅茶" },
  { key: "soft",    label: "ソフトドリンク" },
  { key: "alcohol", label: "アルコール" },
];
